name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Initialize catalog with '...'
        2. Emit metadata with '...'
        3. Query API endpoint '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what you observed (include error messages, logs, etc.)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MetaFuse Version
      description: Which version of MetaFuse are you using?
      placeholder: e.g., 0.4.3
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of MetaFuse is affected?
      options:
        - catalog-core
        - catalog-storage
        - catalog-emitter
        - catalog-api
        - catalog-cli
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 14]
        - Rust version: [output of `rustc --version`]
        - DataFusion version: [if applicable]
      render: markdown
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Relevant log output or error messages (if any)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information
          required: true
        - label: I am using a supported version of MetaFuse
          required: true
